In [2]:
import pandas as pd

In [3]:
Dec2022 = pd.read_csv('Dec22_Data.csv')
Nov2022 = pd.read_csv('Nov22_Data.csv')
Oct2022 = pd.read_csv('Oct22_Data.csv')
Sep2022 = pd.read_csv('Sep22_Data.csv')
Aug2022 = pd.read_csv('Aug22_Data.csv')
Jul2022 = pd.read_csv('Jul22_Data.csv')


summary1 = Jul2022.append(Aug2022)
summary2 = summary1.append(Sep2022)
summary3 = summary2.append(Oct2022)
summary4 = summary3.append(Nov2022)
summary = summary4.append(Dec2022)

In [4]:
summary.rename({"Unnamed: 0":"a"}, axis="columns", inplace=True)
summary.drop(["a"], axis=1, inplace=True)

In [5]:
summary.head(5)

,Date,City,State,Country,Shape,Duration,Summary,Posted,Images
0,7/31/22 22:52,Cuenca,NaN,Ecuador,Light,5 minutes,Triangle shape moving lights,10/8/22,Yes
1,7/31/22 21:59,West Lafayette,OH,USA,Light,4 minutes,Bright circle light moving through sky.,9/9/22,Yes
2,7/31/22 21:45,Burr Ridge,IL,USA,Other,NaN,"Strange red, blue and black craft in the sky a...",9/9/22,Yes
3,7/31/22 21:25,"Lingan, Cape Breton Island",NS,Canada,Cylinder,1-2 minutes,We were waiting for fireworks to start across ...,9/9/22,NaN
4,7/31/22 21:15,Conway,SC,USA,Circle,Less than a minute,Round bright white light go in a straight line...,9/9/22,NaN

In [20]:
USummary = summary.loc[summary['Country'] == 'USA']

In [25]:
# USummary.reset_index(drop=True,inplace=True)
USummary.head(30)

,Date,City,State,Country,Shape,Duration,Summary,Posted,Images,ReportNum
1,7/31/22 21:59,West Lafayette,OH,USA,Light,4 minutes,Bright circle light moving through sky.,9/9/22,Yes,1
2,7/31/22 21:45,Burr Ridge,IL,USA,Other,NaN,"Strange red, blue and black craft in the sky a...",9/9/22,Yes,2
4,7/31/22 21:15,Conway,SC,USA,Circle,Less than a minute,Round bright white light go in a straight line...,9/9/22,NaN,4
5,7/31/22 21:11,Keyser,WV,USA,Light,2 minutes,Saw an orb that interacted with me.,9/9/22,NaN,5
6,7/31/22 20:43,gressham,OR,USA,Unknown,less than a minute,A single soft red light that pulsed three time...,9/9/22,NaN,6
7,7/31/22 20:30,Eddyville,KY,USA,Changing,1minute or more,"3 craft were flying. 2 disappeared 1 hovered, ...",9/9/22,Yes,7
8,7/31/22 20:20,Carpinteria,CA,USA,Diamond,60 seconds,I saw this disk above my head I just can't thi...,9/9/22,NaN,8
9,7/31/22 17:00,Tacoma,WA,USA,Light,25 min,Multiple bright lights,9/9/22,Yes,9
11,7/31/22 09:57,Charlotte,NC,USA,Circle,1 minute,Bright white light that moved fairly quickly t...,9/9/22,NaN,11
12,7/31/22 06:30,Burnet,TX,USA,Circle,5 minutes,Took 3 photos . It changed shape progressively,9/9/22,Yes,12
13,7/31/22 02:30,Seattle,WA,USA,Formation,1 minute,Viewed 3 lights in a line and another single l...,9/9/22,NaN,13
14,7/31/22 02:00,Naples,FL,USA,Rectangle,At least 30 min,Bright white light looks square,9/9/22,Yes,14
16,7/31/22 01:00,Tacoma,WA,USA,Light,3 yrs,"Lights in forest and coming into my room, duri...",9/9/22,NaN,16
17,7/30/22 23:45,Flemington,NJ,USA,Diamond,over 1 hour,Hovering object in the southeast sky about 30 ...,10/8/22,Yes,17
18,7/30/22 23:05,Fremont,CA,USA,Disk,3 seconds,Fastest UFO flying very close,9/9/22,NaN,18
19,7/30/22 23:01,Bella Vista,AR,USA,Cigar,2:00 Minutes,A disk that had lights on it hovered over the ...,9/9/22,NaN,19
20,7/30/22 22:35,Dorchester,MA,USA,Rectangle,2 hours,Looked up & saw a large pulsing ball of light....,9/9/22,Yes,20
21,7/30/22 21:25,Dalton Gardens,ID,USA,Light,1 minute,Satellite type of light moving horizontally we...,9/9/22,NaN,21
22,7/30/22 21:12,Philadelphia,PA,USA,Sphere,5 minutes,Flying orb or sphere that changes colors and p...,9/9/22,NaN,22
23,7/30/22 21:00,Harrisburg,PA,USA,Unknown,N/a,It's orbs all on me,12/22/22,NaN,23
24,7/30/22 20:45,Wexford,PA,USA,Cigar,1/2 hour,"I think it was the chinese ship, it was tumbli...",9/9/22,Yes,24
26,7/30/22 19:28,Newark,NJ,USA,Sphere,10 minutes,25-30 white orbs coming from behind a cloud ov...,9/9/22,Yes,26
27,7/30/22 17:00,Hicksville,NY,USA,Other,At least 1hr,Black orb,9/9/22,Yes,27
28,7/30/22 15:35,Chenoa,NaN,USA,Oval,about 15 sec,Oval moving slightly north east to slightly so...,9/9/22,NaN,28
29,7/30/22 09:20,River Forest,IL,USA,Sphere,About 10 minutes,Saw two silver spherical shapes in the sky whi...,9/9/22,NaN,29
31,7/30/22 02:20,Eudora,KS,USA,Light,5 seconds,I saw a star move then take off,9/9/22,NaN,31
32,7/30/22 01:47,North Dartmouth,MA,USA,Circle,10 seconds,Woke up to see a very bright light emitting sh...,12/22/22,NaN,32
34,7/30/22 01:30,Randolph,VT,USA,Light,Roughly a half hour,My husband and I saw a distinct large light ho...,9/9/22,NaN,34
36,7/30/22 00:30,Maupin,OR,USA,Oval,30 minutes,Unknown Object hovering beyond canyon,9/9/22,NaN,36
37,7/30/22 00:20,Grand Junction,CO,USA,Disk,30 minutes,Some multiple crafts from back porch,9/9/22,NaN,37

In [22]:
USummary['ReportNum'] = USummary.index

C:\Users\13135\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [23]:
USummary.head(5)

,Date,City,State,Country,Shape,Duration,Summary,Posted,Images,ReportNum
1,7/31/22 21:59,West Lafayette,OH,USA,Light,4 minutes,Bright circle light moving through sky.,9/9/22,Yes,1
2,7/31/22 21:45,Burr Ridge,IL,USA,Other,NaN,"Strange red, blue and black craft in the sky a...",9/9/22,Yes,2
4,7/31/22 21:15,Conway,SC,USA,Circle,Less than a minute,Round bright white light go in a straight line...,9/9/22,NaN,4
5,7/31/22 21:11,Keyser,WV,USA,Light,2 minutes,Saw an orb that interacted with me.,9/9/22,NaN,5
6,7/31/22 20:43,gressham,OR,USA,Unknown,less than a minute,A single soft red light that pulsed three time...,9/9/22,NaN,6

In [10]:
USummary.to_csv('summary.csv')